// Local mirror of packages/document-schema preview contracts.
// Keep snake_case fields because the preview JSON is generated by parser-worker.

export type DocumentPreviewStatus =
  | "uploaded"
  | "preview_pending"
  | "preview_processing"
  | "preview_ready"
  | "preview_failed";

export interface DocumentRecord {
  documentId: string;
  clientId: string;
  competenceId: string;
  originalFilename: string;
  fileFormat: "PDF" | "EXCEL" | "CSV" | "TXT" | "DOCX" | "XML" | "ZIP" | string;
  status: DocumentPreviewStatus | string;
  sizeBytes?: number | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export interface DocumentsListResponse {
  items: DocumentRecord[];
  page: number;
  limit: number;
  total: number;
}

export interface BoundingBox {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

export interface PdfToken {
  token_id: string;
  text: string;
  bbox: BoundingBox;
  confidence?: number | null;
}

export interface PdfLine {
  line_id: string;
  text: string;
  bbox: BoundingBox;
  tokens: PdfToken[];
}

export interface PdfTextBlock {
  block_id: string;
  text: string;
  bbox: BoundingBox;
  confidence?: number | null;
  source: string;
}

export interface PdfTableCandidate {
  table_id: string;
  bbox: BoundingBox;
  rows: unknown[];
  columns: unknown[];
  confidence: number;
}

export interface PdfPagePreview {
  page_number: number;
  width: number;
  height: number;
  rotation: number;
  text_blocks: PdfTextBlock[];
  lines: PdfLine[];
  tables: PdfTableCandidate[];
}

export interface PreviewSummary {
  page_count: number;
  sheet_count: number;
  text_block_count: number;
  table_count: number;
}

export interface PdfDocumentPreview {
  document_id: string;
  file_format: "PDF";
  parser_version: string;
  generated_at: string;
  requires_ocr: boolean;
  ocr_reason?: string | null;
  pages: PdfPagePreview[];
  summary: PreviewSummary;
}

export interface ExcelCellPreview {
  cell_id: string;
  address: string;
  row: number;
  column: number;
  column_letter: string;
  value: unknown;
  raw_value: unknown;
  data_type: string;
  is_merged: boolean;
  merged_range?: string | null;
}

export interface ExcelMergedRange {
  range: string;
  start_row: number;
  start_column: number;
  end_row: number;
  end_column: number;
}

export interface ExcelDetectedHeader {
  row: number;
  values: string[];
  confidence: number;
}

export interface ExcelTableCandidate {
  table_id: string;
  range: string;
  header_row: number;
  start_row: number;
  end_row: number;
  confidence: number;
}

export interface ExcelSheetPreview {
  sheet_id: string;
  name: string;
  index: number;
  max_row: number;
  max_column: number;
  cells: ExcelCellPreview[];
  merged_cells: ExcelMergedRange[];
  detected_headers: ExcelDetectedHeader[];
  detected_tables: ExcelTableCandidate[];
}

export interface ExcelDocumentPreview {
  document_id: string;
  file_format: "XLSX" | "XLS";
  parser_version: string;
  generated_at: string;
  requires_ocr: false;
  sheets: ExcelSheetPreview[];
  summary: PreviewSummary;
}

export type ParsedDocumentPreview = PdfDocumentPreview | ExcelDocumentPreview;

export interface DocumentPreviewApiResponse {
  documentId: string;
  status: DocumentPreviewStatus;
  preview: ParsedDocumentPreview | null;
  errorMessage?: string | null;
}

export interface DocumentPreviewStatusResponse {
  documentId: string;
  status: DocumentPreviewStatus;
  parsingJobId?: string | null;
  previewId?: string | null;
  errorMessage?: string | null;
}

export interface PreviewRequestResponse {
  documentId: string;
  parsingJobId: string;
  status: DocumentPreviewStatus;
}

export function isPdfPreview(preview: ParsedDocumentPreview | null): preview is PdfDocumentPreview {
  return preview?.file_format === "PDF";
}

export function isExcelPreview(preview: ParsedDocumentPreview | null): preview is ExcelDocumentPreview {
  return preview?.file_format === "XLSX" || preview?.file_format === "XLS";
}
