from enum import StrEnum


class ClientStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ARCHIVED = "ARCHIVED"


class TaxRegime(StrEnum):
    SIMPLES_NACIONAL = "SIMPLES_NACIONAL"
    LUCRO_PRESUMIDO = "LUCRO_PRESUMIDO"
    LUCRO_REAL = "LUCRO_REAL"
    MEI = "MEI"
    IMUNE_ISENTA = "IMUNE_ISENTA"
    NAO_INFORMADO = "NAO_INFORMADO"


class CompetencyStatus(StrEnum):
    OPEN = "OPEN"
    PREPARING = "PREPARING"
    READY_FOR_CONFERENCE = "READY_FOR_CONFERENCE"
    IN_CONFERENCE = "IN_CONFERENCE"
    REVIEW = "REVIEW"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class ClientRole(StrEnum):
    CLIENT_MANAGER = "CLIENT_MANAGER"
    CLIENT_OPERATOR = "CLIENT_OPERATOR"
    CLIENT_VIEWER = "CLIENT_VIEWER"


class LinkStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class ResponsibilityArea(StrEnum):
    ACCOUNTING = "ACCOUNTING"
    FISCAL = "FISCAL"
    PAYROLL = "PAYROLL"
    LEGAL = "LEGAL"
    GENERAL = "GENERAL"


class AuditEventType(StrEnum):
    CLIENT_CREATED = "CLIENT_CREATED"
    CLIENT_UPDATED = "CLIENT_UPDATED"
    CLIENT_DISABLED = "CLIENT_DISABLED"
    CLIENT_ARCHIVED = "CLIENT_ARCHIVED"
    CLIENT_RESTORED = "CLIENT_RESTORED"
    CLIENT_FOLDER_UPDATED = "CLIENT_FOLDER_UPDATED"
    CLIENT_FOLDER_PREVIEWED = "CLIENT_FOLDER_PREVIEWED"
    CLIENT_USER_LINKED = "CLIENT_USER_LINKED"
    CLIENT_USER_UPDATED = "CLIENT_USER_UPDATED"
    CLIENT_USER_UNLINKED = "CLIENT_USER_UNLINKED"
    CLIENT_COMPETENCY_CREATED = "CLIENT_COMPETENCY_CREATED"
    CLIENT_COMPETENCY_UPDATED = "CLIENT_COMPETENCY_UPDATED"
    CLIENT_COMPETENCY_STATUS_CHANGED = "CLIENT_COMPETENCY_STATUS_CHANGED"
    CLIENT_COMPETENCY_CLOSED = "CLIENT_COMPETENCY_CLOSED"
    CLIENT_COMPETENCY_ARCHIVED = "CLIENT_COMPETENCY_ARCHIVED"
    CLIENT_ACCESS_DENIED = "CLIENT_ACCESS_DENIED"


class Permission:
    CLIENTS_READ = "clients:read"
    CLIENTS_CREATE = "clients:create"
    CLIENTS_UPDATE = "clients:update"
    CLIENTS_DISABLE = "clients:disable"
    CLIENTS_ARCHIVE = "clients:archive"
    CLIENT_USERS_READ = "client-users:read"
    CLIENT_USERS_MANAGE = "client-users:manage"
    COMPETENCIES_READ = "client-competencies:read"
    COMPETENCIES_CREATE = "client-competencies:create"
    COMPETENCIES_UPDATE = "client-competencies:update"
    COMPETENCIES_CLOSE = "client-competencies:close"
    COMPETENCIES_ARCHIVE = "client-competencies:archive"
    FOLDERS_READ = "client-folders:read"
    FOLDERS_UPDATE = "client-folders:update"
    FOLDERS_PREVIEW = "client-folders:preview"
    CONTEXT_READ = "client-context:read"

