from enum import StrEnum


class IdentityAuditEventType(StrEnum):
    AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
    AUTH_LOGIN_FAILED = "AUTH_LOGIN_FAILED"
    AUTH_LOGOUT = "AUTH_LOGOUT"
    AUTH_LOGOUT_ALL = "AUTH_LOGOUT_ALL"
    AUTH_TOKEN_REFRESH = "AUTH_TOKEN_REFRESH"
    AUTH_PASSWORD_CHANGED = "AUTH_PASSWORD_CHANGED"
    AUTH_PASSWORD_RESET_BY_ADMIN = "AUTH_PASSWORD_RESET_BY_ADMIN"
    AUTH_USER_DISABLED = "AUTH_USER_DISABLED"
    AUTH_USER_ENABLED = "AUTH_USER_ENABLED"
    AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"
